// Code generated by "stringer -type=Season"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Winter-1]
	_ = x[Summer-2]
	_ = x[Monsoon-3]
	_ = x[Fall-4]
	_ = x[Spring-5]
}

const _Season_name = "UnknownWinterSummerMonsoonFallSpring"

var _Season_index = [...]uint8{0, 7, 13, 19, 26, 30, 36}

func (i Season) String() string {
	if i < 0 || i >= Season(len(_Season_index)-1) {
		return "Season(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Season_name[_Season_index[i]:_Season_index[i+1]]
}
